#!/bin/bash

PROGRAM="hwb"
VERSION="1.0"

capitalize=false
color="auto"
greeting="Hello"
print_world=false

TEMP=$(getopt -o cg:hvw \
    --long capitalize,color:,greeting:,help,version,world \
    -n "$PROGRAM" -- "$@")

if [ $? -ne 0 ]; then
    exit 1
fi

eval set -- "$TEMP"

while true; do
    case "$1" in
        -c|--capitalize)
            capitalize=true
            shift
            ;;
        --color)
            color="$2"
            shift 2
            ;;
        -g|--greeting)
            greeting="$2"
            shift 2
            ;;
        -w|--world)
            print_world=true
            shift
            ;;
        -h|--help)
            cat <<EOF
Usage: $PROGRAM [OPTIONS] [NAMES...]

Options:
  -c, --capitalize        capitalize names/world
      --color=WHEN        color output (never, auto, always)
  -g, --greeting=TEXT     change greeting (default: Hello)
  -w, --world             also print "Hello, world!"
  -h, --help              show this help
  -v, --version           show version
EOF
            exit 0
            ;;
        -v|--version)
            echo "$PROGRAM $VERSION"
			echo "Copyright (c) 2026"
            exit 0
            ;;
        --)
            shift
            break
            ;;
        *)
            exit 1
            ;;
    esac
done

use_color=false
case "$color" in
    always) use_color=true ;;
    never)  use_color=false ;;
    auto)
        if [ -t 1 ]; then
            use_color=true
        fi
        ;;
    *)
        echo "Invalid --color value"
        exit 1
        ;;
esac

colorize() {
    if $use_color; then
        printf "\033[1;32m%s\033[0m" "$1"
    else
        printf "%s" "$1"
    fi
}

cap() {
    if $capitalize; then
        printf "%s" "$1" | awk '{print toupper(substr($0,1,1)) substr($0,2)}'
    else
        printf "%s" "$1"
    fi
}

print_line() {
    name=$(cap "$1")
    greet=$(cap "$greeting")
    printf "%s, %s !\n" "$greet" "$(colorize "$name")"
}

if [ $# -eq 0 ] || $print_world; then
    print_line "world"
fi

for name in "$@"; do
    print_line "$name"
done
